debug seven

diff --git a/azure-templates/source-version.yml b/azure-templates/source-version.yml
--- a/azure-templates/source-version.yml
+++ b/azure-templates/source-version.yml
@@ -1,20 +1,16 @@
 steps:
-  - task: Bash@3
-    displayName: Get short git hash
-    inputs:
-      targetType: 'inline'
-      script: |
-        short_hash=`git rev-parse --short=7 HEAD`
-        echo ""
-        echo "Full git hash:  $(Build.SourceVersion)"
-        echo "Short git hash: $short_hash"
-        echo ""
-        ## Fail step if full hash does not start with short hash
-        if [[ $(Build.SourceVersion) != $short_hash* ]]; then
-          echo "--> Hashes do not match! Aborting."
-          exit 1
-        fi
-        echo "--> Hashes match. Storing short hash for subsequent steps."
-        ## Store variable for subsequent steps
-        echo "##vso[task.setvariable variable=short_hash;isreadonly=true;isoutput=true]$short_hash"
-      id: get_short_hash
+  - bash: |
+      short_hash=`git rev-parse --short=7 HEAD`
+      echo ""
+      echo "Full git hash:  $(Build.SourceVersion)"
+      echo "Short git hash: $short_hash"
+      echo ""
+      ## Fail step if full hash does not start with short hash
+      if [[ $(Build.SourceVersion) != $short_hash* ]]; then
+        echo "--> Hashes do not match! Aborting."
+        exit 1
+      fi
+      echo "--> Hashes match. Storing short hash for subsequent steps."
+      ## Store variable for subsequent steps
+      echo "##vso[task.setvariable variable=short_hash;isreadonly=true;isoutput=true]$short_hash"
+    name: get_short_hash
